[package]
name = "luadec"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.91"
directories = "5.0.1"
lazy_static = "1.5.0"
mlua = {version="0.9", features=["vendored", "lua54", "async", "send"]}
serde = "1.0.214"
serde_json = "1.0.132"
